AppDEMO/ViewModels/RegistrationForrm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AppDEMO.ViewModels
{
    
    public class RegistrationForrm
    {
        private string firstName;
        private string lastName;
        private string address;
        private string email;
        private string phoneNumber;
        private string course;
        private string dateOfBirth;

        public RegistrationForrm()
        {
        }

        public RegistrationForrm(string firstName, string lastName, string address, string email, string phoneNumber, string course, string dateOfBirth)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.address = address;
            this.email = email;
            this.phoneNumber = phoneNumber;
            this.course = course;
            this.dateOfBirth = dateOfBirth;
        }

        public string FirstName { get => firstName; set => firstName = value; }
        public string LastName { get => lastName; set => lastName = value; }
        public string Address { get => address; set => address = value; }
        public string Email { get => email; set => email = value; }
        public string PhoneNumber { get => phoneNumber; set => phoneNumber = value; }
        public string Course { get => course; set => course = value; }
        public string DateOfBirth { get => dateOfBirth; set => dateOfBirth = value; }
    }
}

AppDEMO/Controllers/FormController.cs
using AppDEMO.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net.Http;
using Newtonsoft.Json.Linq;

namespace AppDEMO.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }

        // GET: Form/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Form/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Form/Create
        [HttpPost]
        public ActionResult Create(RegistrationForrm collection)
        {
            try
            {
                // TODO: Add insert logic here

                return Json(new { result = true }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View();
            }
        }

        // GET: Form/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Form/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Form/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Form/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        [Route("Form/SpringCreate")]
        public ActionResult SpringCreate()
        {
            return View();
        }

        [HttpGet]
        [Route("Form/SpringCongratulations")]
        public ActionResult SpringCongratulations()
        {
            return View();
        }
        
    }
}

AppDEMO/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppDEMO.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AppDEMO/Views/Form/Create.cshtml
    <form id="form1">
        <h1>Course Request</h1>
        <br />
        <div>

            First Name:<input id="firstName" class="form-control" /> <br />
            Last Name:<input id="lastName" class="form-control" /> <br />
            Address:<input id="address" class="form-control" /> <br />
            Emal:<input id="email" class="form-control" /> <br />
            Phone Number:<input id="phoneNumber" class="form-control" /> <br />
            Course:<input id="course" class="form-control" /> <br />
            Date Of Birth:<input id="dateOfBirth" type="date" class="form-control" /> <br />
        </div>

        <button type="button" id="save" class="btn btn-primary" onclick="guardarDatosForm();">Save</button>

    </form>

    <script>
    function guardarDatosForm(){
        var nuevo = {
            firstName: $('#firstName').val(),
            lastName: $('#lastName').val(),
            address: $('#address').val(),
            email: $('#email').val(),
            phoneNumber: $('#phoneNumber').val(),
            course: $('#course').val(),
            dateOfBirth: $('#dateOfBirth').val()
        }

        $.ajax({
            url: '@Url.Action("Create", "Form")',
            type: 'POST',
            data: {
                collection: nuevo
            },
            success: function (resultado) {
                
                location.href = "../Form/Index";
            },
            error: function (error) {
                console.log('Se encontró el siguiente error --> ' + error.state + ' : ' + error.statusText);
            }
        });
    }
    </script>

AppDEMO/Views/Form/Index.cshtml
<link rel="stylesheet" href="~/Scripts/index.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap">

<div class="container">
    <button type="button" id="save" class="btn btn-primary" onclick="init();">To List</button>
    <br />
    <div class="col col-md-7">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Address</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone Number</th>
                    <th scope="col">Course</th>
                    <th scope="col">Date Of Birth</th>
                </tr>
            </thead>
            <tbody id="tbody">
            </tbody>
        </table>
    </div>
    <div class="col col-md-5">
        <img src="~/images/list.svg" />
    </div>

</div>

<script>
    
    
    function init() {
        
        $.ajax({
            url: 'http://localhost:8080/getAllForms',
            method: 'GET',
            headers: { "Accept": "application/json; odata=verbose" },
            success: function (resultado) {
                createTable(resultado);
            },
            error: function (error) {
                console.log('Se encontró el siguiente error --> ' + error.state + ' : ' + error.statusText);
            }
        });
    }

    function createTable(resultado) {

        var tbody = document.querySelector("#tbody");
        
        resultado.forEach(item => {
            
            var tr = document.createElement("tr");
            //firstName
            var tdfirstName = document.createElement("td");
            var txtfirstName = document.createTextNode(item.firstName);
            tdfirstName.appendChild(txtfirstName);
            tr.appendChild(tdfirstName);

            //lastName
            var tdlastName = document.createElement("td");
            var txtlastName = document.createTextNode(item.lastName);
            tdlastName.appendChild(txtlastName);
            tr.appendChild(tdlastName);
            //address
            var tdaddress = document.createElement("td");
            var txtaddress = document.createTextNode(item.address);
            tdaddress.appendChild(txtaddress);
            tr.appendChild(tdaddress);
            //email
            var tdemail = document.createElement("td");
            var txtemail = document.createTextNode(item.email);
            tdemail.appendChild(txtemail);
            tr.appendChild(tdemail);
            //phoneNumber
            var tdphoneNumber = document.createElement("td");
            var txtphoneNumber = document.createTextNode(item.phoneNumber);
            tdphoneNumber.appendChild(txtphoneNumber);
            tr.appendChild(tdphoneNumber);
            //course
            var tdcourse = document.createElement("td");
            var txtcourse = document.createTextNode(item.course);
            tdcourse.appendChild(txtcourse);
            tr.appendChild(tdcourse);
            //dateOfBirth
            var tddateOfBirth = document.createElement("td");
            var txtdateOfBirth = document.createTextNode(item.dateOfBirth);
            tddateOfBirth.appendChild(txtdateOfBirth);
            tr.appendChild(tddateOfBirth);
            tbody.appendChild(tr);
        });
        
    }
        

</script>

AppDEMO/Views/Form/SpringCongratulations.cshtml
<link rel="stylesheet" href="~/Scripts/index.css">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap">

<div class="card">
    <img src="~/images/congratulations.svg" alt="birthday" class="birthday">
    <div class="text">
        <h1>Congratulations!</h1>
        <p>The form has been sent correctly</p>
        <a class="btn btn-primary" href='@Url.Action("SpringCreate", "Form")'>Accept</a>
    </div>
    <div class="space"></div>
</div>

AppDEMO/Views/Form/SpringCreate.cshtml
<div class="container">
    <br />
    <h2>Create Form</h2>
    <br />

    <div class="col col-md-6">

        <form>


            <div class="col col-md-12">
                <label for="firstName">First Name</label>
                <div>
                    <input class="form-control" type="text" name="firstName" id="firstName" required />
                </div>
            </div>
            <div class="col col-md-12">
                <br />
                <label for="lastName">Last Name</label>
                <div>
                    <input class="form-control" type="text" name="lastName" id="lastName" required />
                </div>
            </div>

            <div class="col col-md-12">
                <br />
                <label for="address">Address</label>
                <div>
                    <input class="form-control" type="text" name="address" id="address" required />
                </div>
            </div>
            <div class="col col-md-12">
                <br />
                <label for="email">Email</label>
                <div>
                    <input class="form-control" type="email" name="email" id="email" required />
                </div>
            </div>
            <br />
            <div class="col col-md-12">
                <label for="phoneNumber">Phone Number</label>
                <div>
                    <input class="form-control" type="text" name="phoneNumber" id="phoneNumber" required />
                </div>
            </div>
            <div class="col col-md-12">
                <br />
                <label for="course">Course</label>
                <div>
                    <input class="form-control" type="text" name="course" id="course" required />
                </div>
            </div><br />
            <div class="col col-md-12">
                <br />
                <label for="dateOfBirth">Date Of Birth</label>
                <div>
                    <input class="form-control" type="date" name="dateOfBirth" id="dateOfBirth" required />
                </div>
            </div>
            <br />
            <div class="col col-md-12">
                <br />
                <div>
                    <button type="button" id="save" class="btn btn-primary" onclick="guardarDatosForm();">Save</button>
                </div>
            </div>
        </form>

    </div>
    <div class="col col-md-6">

        <img src="~/images/createForm.svg" />
    </div>

    </div>

<script>
    function guardarDatosForm(){
        var form = {
                firstName: $('#firstName').val(),
                lastName: $('#lastName').val(),
                address: $('#address').val(),
                email: $('#email').val(),
                phoneNumber: $('#phoneNumber').val(),
                course: $('#course').val(),
                dateOfBirth: $('#dateOfBirth').val()
        }
        $.ajax({
            url: 'http://localhost:8080/createForm',
            method: 'POST',
            data: JSON.stringify(form),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (resultado) {

                location.href = "../Form/SpringCongratulations";
            },
            error: function (error) {
                console.log('Se encontró el siguiente error --> ' + error.state + ' : ' + error.statusText);
            }
        });
    }
</script>

AppDEMO/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AppDEMO/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AppDEMO/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AppDEMO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Create Form", "SpringCreate", "Form", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Request List", "Index", "Form", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>